---
- hosts: 172.31.20.201
  become: True
  vars:
    - apache_port: 8080
  tasks:
    - name: Install apache server
      yum:
        name: httpd
        state: present
    - name: enable on reboot
      service:
        name: httpd
        enabled: True
    - name: start apache server
      service:
        name: httpd
        state: started

    - name: copying files to apache 
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: change port number
      template:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf
      notify: 
        - restart apache
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
