---
- hosts: 172.31.21.217
  become: True
  vars:
    - apache_port: 80
    - apache_deploy_path: /var/www/html
    - apache_conf_path: /etc/httpd/conf  
  tasks:
    - name: Install Apache Server
      yum:
        name: httpd
        state: present
    - name: Enable on reboot
      service:
        name: httpd
        enabled: True
    - name: Start Apache Server
      service:
        name: httpd
        state: started  
    - name: Copy file from CM to Apache Server
      copy:
        src: index.html
        dest: "{{apache_deploy_path}}/index.html"
      notify:
        - Restart Apache
    - name: Change Port Number
      template:
       src: httpd.conf
       dest: "{{apache_conf_path}}/httpd.conf"
      notify:
         - Restart Apache
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
